#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Redline keeps its credentials in .env.local, which is gitignored. Never .env.
ENV_FILE=".env.local"

MIGRATION="supabase/migrations/20260916120000_red_lines.sql"

# copy_file_to_clipboard PATH — best effort, so the human can paste the
# migration straight into the SQL editor instead of opening the file.
copy_file_to_clipboard() {
  if   command -v clip.exe >/dev/null 2>&1; then clip.exe < "$1"
  elif command -v pbcopy   >/dev/null 2>&1; then pbcopy   < "$1"
  elif command -v xclip    >/dev/null 2>&1; then xclip -selection clipboard < "$1"
  elif command -v wl-copy  >/dev/null 2>&1; then wl-copy  < "$1"
  else return 1
  fi
}

banner "Connect Redline to Supabase"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the project"
say "Redline needs one Supabase project. It holds your red lines and nothing"
say "else — the text of your contract is never written to it."
open_url "https://supabase.com/dashboard/new"
step "Pick an organisation, name the project (redline is fine)."
step "Choose a region near you, and save the database password somewhere safe."
step "Click 'Create new project' and wait for it to finish provisioning."
note "Provisioning takes a minute or two. Wait for the dashboard to go green."
pause "Press Enter once the project is ready"

say ""
step "Look at the dashboard URL. It reads .../dashboard/project/<ref>"
ask SUPABASE_PROJECT_REF "Paste just the <ref> part:"
if [[ -z "${SUPABASE_PROJECT_REF:-}" ]]; then
  warn "No project ref, so the next stages will open generic pages you'll have"
  warn "to click through to your project yourself."
  SUPABASE_PROJECT_REF="_"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Copy the URL and the key"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
say "This page lists every key the project has."
step "Copy the Project URL. It looks like https://abcdefgh.supabase.co"
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
say ""
step "Now the public client key. Depending on how new the project is it is"
step "labelled either 'anon public' (a long eyJ... token) or 'publishable'"
step "(starts sb_publishable_). Either one works here — copy whichever you see."
note "Both are meant to be public: they ship in the browser bundle. The key"
note "you must never paste here is the service_role / secret one."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste that key:"

if [[ "${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}" == *"service_role"* ]]; then
  warn "That looks like a service_role key. Stop and copy the public one instead."
  exit 1
fi

write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the table"
say "One table, red_lines, with row level security on and owner-only policies."
say "The migration is written to be safe to run more than once."
if copy_file_to_clipboard "$MIGRATION"; then
  say ""
  printf '  %s✓ the migration is on your clipboard%s\n' "$GREEN" "$RESET"
else
  say ""
  note "Couldn't reach a clipboard. Open this file and copy it by hand:"
  note "  $MIGRATION"
fi
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
step "Paste it into the SQL editor."
step "Click Run (or press Ctrl+Enter)."
step "You want 'Success. No rows returned'."
pause "Press Enter once it has run"

open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/editor"
step "Check that a red_lines table is now listed in the table editor."
if ! confirm "Is red_lines there?"; then
  warn "Stop here and read the SQL editor's error before going on."
  warn "Nothing after this will work without the table."
  exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Let the magic link come back"
say "Signing in sends a link by email. Supabase will only follow that link"
say "back to a URL you have allowed, so localhost has to be on the list."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/url-configuration"
step "Set Site URL to:            http://localhost:3000"
step "Under Redirect URLs, Add:   http://localhost:3000/**"
step "Save."
note "Redline sends readers back to /review after they sign in, which the"
note "/** pattern covers. Add your production URL here too when you deploy."
pause "Press Enter once you've saved"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check it took"
say "NEXT_PUBLIC_ values are baked in when the server starts, so the running"
say "dev server cannot see what we just wrote."
step "Stop the dev server (Ctrl+C in its terminal) and run pnpm dev again."
pause "Press Enter once it has restarted"
open_url "http://localhost:3000/review"
step "Scroll to Red lines. Instead of 'no account set up' you should now see"
step "somewhere to enter your email address."
step "Enter it, then open the link in the email that arrives."
say ""
if confirm "Are you signed in?"; then
  say ""
  say "Add a red line, sign out, and sign back in. It should still be there."
else
  warn "If the panel still says no account is set up, the env values did not"
  warn "reach the build: check .env.local and restart the dev server again."
  warn "If the email never arrives, check spam, then Authentication → Logs"
  warn "in the dashboard."
fi

summary
